import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-buy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <Navbar />
        <ToastContainer/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
