import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-buy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
